# Generated by Django 4.2.2 on 2023-07-17 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotaw_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Перс', 'verbose_name_plural': 'Персы'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AlterModelOptions(
            name='topclass',
            options={'verbose_name': 'Топ параметр', 'verbose_name_plural': 'Топ параметры'},
        ),
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=228),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=228),
            preserve_default=False,
        ),
    ]
