# Generated by Django 4.2.2 on 2023-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaw_app', '0002_alter_hero_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(max_length=228, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(max_length=228, unique=True),
        ),
    ]
