# Generated by Django 4.2.2 on 2023-07-19 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotaw_app', '0003_alter_hero_slug_alter_position_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='skill1_disc',
        ),
        migrations.AddField(
            model_name='hero',
            name='skill_1_disc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='disc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skill_2_disc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skill_3_disc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='ultimate_disc',
            field=models.TextField(),
        ),
    ]
